from __future__ import annotations

import json
from pathlib import Path
from uuid import NAMESPACE_URL, uuid5

from translume_adapters.errors import ProviderUnavailableError
from translume_schemas.entities import NormalizedEntitySet
from translume_schemas.graph import GraphEvidenceArtifact
from translume_schemas.tools import ToolRunArtifact


class ToolUniverseProvider:
    """Governed ToolUniverse adapter using local workflow result files.

    The MVP product path accepts only allow-listed workflows and requires local
    configured evidence files generated by ToolUniverse/service jobs. It does
    not synthesize successful tool output when ToolUniverse is absent.
    """

    def __init__(self, allowed_workflows: set[str], evidence_dir: Path) -> None:
        self._allowed_workflows = frozenset(allowed_workflows)
        self._evidence_dir = evidence_dir

    async def run_workflows(
        self,
        *,
        workflows: list[str],
        entities: NormalizedEntitySet,
        graph: GraphEvidenceArtifact,
    ) -> list[ToolRunArtifact]:
        """Load allow-listed ToolUniverse workflow outputs.

        Acceptance criteria:
            1. Only allow-listed workflows can run.
            2. Missing evidence files raise `ProviderUnavailableError`.
            3. Every output is normalized to `ToolRunArtifact`.
            4. Tool output cannot enter the final narrative directly.
            5. No remote model provider is called.

        Args:
            workflows: Workflow names.
            entities: Normalized entities.
            graph: Graph evidence artifact.

        Returns:
            Tool run artifacts.
        """
        artifacts: list[ToolRunArtifact] = []
        entity_ids = [entity.entity_id for entity in entities.entities]
        for workflow in workflows:
            if workflow not in self._allowed_workflows:
                raise ValueError(f"workflow is not allow-listed: {workflow}")
            path = self._evidence_dir / f"{workflow}.json"
            if not path.exists():
                raise ProviderUnavailableError(
                    f"ToolUniverse workflow output is missing: {path}. "
                    "Run ToolUniverse evidence workflow before enabling MIMS-required mode."
                )
            payload = json.loads(path.read_text(encoding="utf-8"))
            artifact_id = f"artifact_{uuid5(NAMESPACE_URL, entities.artifact_id + workflow).hex[:16]}"
            artifacts.append(
                ToolRunArtifact(
                    artifact_id=artifact_id,
                    workflow=workflow,
                    input_entity_ids=entity_ids,
                    summary=str(payload.get("summary", "")),
                    evidence_items=[
                        {str(key): str(value) for key, value in item.items()}
                        for item in payload.get("evidence_items", [])
                    ],
                    warnings=[str(item) for item in payload.get("warnings", [])],
                    requires_human_review=True,
                )
            )
        return artifacts
